version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/permits_db
      - SESSION_SECRET=your-secure-session-secret-change-this
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=permits_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: